/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driver` | `/driver`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driver/login` | `/driver/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driver/signup` | `/driver/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider` | `/rider`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider/login` | `/rider/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider/signup` | `/rider/signup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/driver` | `/driver`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/driver/login` | `/driver/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/driver/signup` | `/driver/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rider` | `/rider`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rider/login` | `/rider/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rider/signup` | `/rider/signup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/driver${`?${string}` | `#${string}` | ''}` | `/driver${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/driver/login${`?${string}` | `#${string}` | ''}` | `/driver/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/driver/signup${`?${string}` | `#${string}` | ''}` | `/driver/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rider${`?${string}` | `#${string}` | ''}` | `/rider${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rider/login${`?${string}` | `#${string}` | ''}` | `/rider/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rider/signup${`?${string}` | `#${string}` | ''}` | `/rider/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driver` | `/driver`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driver/login` | `/driver/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driver/signup` | `/driver/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider` | `/rider`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider/login` | `/rider/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider/signup` | `/rider/signup`; params?: Router.UnknownInputParams; };
    }
  }
}
